default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username:
  password:
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
