default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username:
  password:

development: &development
  adapter: postgresql
  encoding: unicode
  database: local_db
  pool: 5
  username: ayrtonaoki
  password:

test:
  <<: *development

production:
  <<: *default
